language: node_js
node_js:
- '4.4'

script:
- gulp lint
- gulp build
- gulp package
- gulp bower

deploy:
# Creates a tag containing dist files and bower.json
# Requires GITHUB_AUTH_TOKEN and GITHUB_AUTH_EMAIL environment variables
# IMPORTANT: the script has to be set executable in the Git repository (error 127)
# https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-225025939
# http://stackoverflow.com/a/15572639
- provider: script
  script: ./scripts/release.sh
  skip_cleanup: true
  on:
    branch: release
- provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file:
  - "./dist/Chart.Deferred.js"
  - "./dist/Chart.Deferred.min.js"
  - "./dist/Chart.Deferred.js.zip"
  skip_cleanup: true
  on:
    tags: true
